blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/FlexionTech/dbmn/discussions/categories/q-a
    about: Ask questions and get help from the community
  - name: Ideas & Feature Discussion
    url: https://github.com/FlexionTech/dbmn/discussions/categories/ideas
    about: Discuss feature ideas before creating a formal request
